auto: true
pygments: true
server: true
server_port: 8080
permalink: /:categories/:title
lsi: false
exclude: ["package.json", "Gruntfile.js", "README.md", "node_modules"]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

